// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Tasks
export const GET_TASKS_LIST_SUCCESS = "GET_TASKS_LIST_SUCCESS";
export const GET_TASKS_LIST_FAILURE = "GET_TASKS_LIST_FAILURE";

export const GET_TASK_BY_ID_SUCCESS = "GET_TASK_BY_ID_SUCCESS";
export const GET_TASK_BY_ID_FAILURE = "GET_TASK_BY_ID_FAILURE";

export const POST_TASKS_SUCCESS = "POST_TASKS_SUCCESS";
export const POST_TASKS_FAILURE = "POST_TASKS_FAILURE";

export const UPDATE_TASKS_SUCCESS = "UPDATE_TASKS_SUCCESS";
export const UPDATE_TASKS_FAILURE = "UPDATE_TASKS_FAILURE";

export const DELETE_TASKS_SUCCESS = "DELETE_TASKS_SUCCESS";
export const DELETE_TASKS_FAILURE = "DELETE_TASKS_FAILURE";
